### ISSUE TITLE
serial port config

### ISSUE THREAD

**Issue by nution101** [slifty/opened-captions#3]
Trying to open the line in config.js for adding the serial port as an input. My serial is open, Ive got caption data coming into it using the textgrabber box. I can see the data coming in down the line using moserial app. However Im a bit confused.

Ive uncommented the line for adding the serial port and commented out the line for server input, but where it asks for location " " (on the serial port settings) Im at a loss of what to put there. My specific serial port is located at /dev/ttyUSB0. Ive tried /dev/ttyUSB0 and ttyUSB0 as the location but its throwing an error with no reference back to where it is coming from (when I run "node app"). 

I cant see in your documentation or on the web any reference for what parameters the serial port needs in the location area. Any help would be greatly appreciated. Thank you so much!

**Comment by slifty** [comment]
Glad that this wound up working -- I should have closed it back when it was resolved but better late than never!
