### ISSUE TITLE
following install docs results in error on app launch

### ISSUE THREAD

**Issue by ryanpitts** [slifty/opened-captions#5]
I followed both the scripted and manual installation instructions, and hit the same error in both cases: `TypeError: Object #<Server> has no method 'configure'`

![screen shot 2014-06-26 at 9 12 46 pm](https://cloud.githubusercontent.com/assets/56477/3407631/8a95f820-fdb1-11e3-8e10-a64a0cceae10.png)

It looks like that method may be deprecated in the latest version of socket.io-client? https://github.com/Automattic/socket.io/issues/1517

I'm not positive -- I did try manually installing a few previous versions of socket.io-client to see if that resolved the problem, but no luck so far.

**Comment by slifty** [comment]
This issue was fixed, and then became not so fixed again (see #11) -- I'm closing this issue since it is stale.
