### ISSUE TITLE
Project Over/Server down?

### ISSUE THREAD

**Issue by ruricu** [slifty/opened-captions#6]
I just stumbled upon this project yesterday, wishing to use the "API" to build into my own project. I understand that the openedcaptions.com server wasn't ever exactly in a permanent home. Has it been retired? Does anyone else have a C-Span openedcaptions server running? I'd like to think this project can spawn more than just drinking games or "talk like a pirate" political commentary, but actually become a platform for political accountability-based applications.

**Comment by janislejins** [comment]
Hi Is the stream ever coming back?

**Comment by slifty** [comment]
Sorry for not responding here but the stream is indeed back (and has been for about a year) -- openedcaptions.com
